#!/usr/bin/env bash
#this script diplays: to infinity and beyond indefinitely with a sleep 2 between each iteration I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
while true;
do 
	echo "To infinity and beyond"
	sleep 2
done
